export default {
  mainColor: "#7179f7",
  // mainColor: "#00BCC9",
  backGround: "#FEE2E2",
  mainTheme: "#F2F1FD",
  heard: "#f54",
  heardDark: "#f54",
  accent: "#7fc",
  blue: "#5555ff",
  white: "#ffff",
  // while2: "#fdfdfd",
  while2: "#fcfcfb",
  whileOpacity: "rgba(255, 255, 255, 0.5)",
  black: "#000",
  blackOpacity: "#2d2d44",
  gray: "#666",
  darkGray: "#BBBDC1",
  darkGray2: "#f8f8F8",

  red: "#F52A2A",
  light: "#F1F1F1",
  green: "#00B761",
  textLight: "#CDCDCD",
  yellow: "#F5CA48",
  textDark: "#313234",
  primary: "#F5CA48",
  blueMain: "#7179f7",
  blueSd: "#819ff2",
  blueTheme: "#bfd9f0",
  greenTheme: "#EDFFEF",
  pinkTheme: "#ffeded",
  purple: "#AD40AF",

  transparent: "transparent",
};

// header: {
//   height: 75,
//   // flex: 1,
//   width: "25%",
//   // borderWidth: 2,
//   justifyContent: "center",
//   alignContent: "center",
//   alignItems: "center",
// },
// image: {
//   width: "100%",
//   height: "100%",

//   // borderTopLeftRadius: 20,
//   // borderTopRightRadius: 20,
//   // alignSelf: "center",
// },
