import {
  bg1,
  bg2,
  bg3,
  bg4,
  bg5,
  bg6,
  bg7,
  promoBg1,
  promoBg2,
  promoBg3,
} from "../public/assets/image";

export const product_tabs = [
  { id: 0, name: "Chi tiết" },
  { id: 1, name: "Cửa hàng" },
  { id: 2, name: "Bình luận" },
];

export const roles = [
  { id: 1, name: "ROLE_USER" },
  { id: 2, name: "ROLE_SALER" },
  { id: 3, name: "ROLE_ADMIN" },
];

// export const typeList = [
//   "Sneakers",
//   "Sandals",
//   "Flip flops",
//   "High - Heels",
//   "Oxfords",
//   "Athletics",
//   "Boots - Ankle",
//   "Baby",
// ];

export const suggestions = [
  { value: "Nike" },
  { value: "Adidas" },
  { value: "Puma" },
  { value: "Reebok" },
  { value: "Vans" },
  { value: "Converse" },
  { value: "New Balance" },
  { value: "ASICS" },
  { value: "Skechers" },
  { value: "Under Armour" },
  { value: "Jordan" },
  { value: "Salomon" },
  { value: "Merrell" },
  { value: "Brooks" },
  { value: "Hoka One One" },
  { value: "Timberland" },
  { value: "Dr. Martens" },
  { value: "Clarks" },
  { value: "ECCO" },
  { value: "Crocs" },
  { value: "Gucci" },
  { value: "Balenciaga" },
  { value: "Louis Vuitton" },
  { value: "Prada" },
  { value: "Fendi" },
  { value: "Versace" },
  { value: "Givenchy" },
  { value: "Chanel" },
  { value: "Christian Louboutin" },
  { value: "Yeezy" },
  { value: "Balmain" },
  { value: "Valentino" },
  { value: "Dolce & Gabbana" },
  { value: "Jimmy Choo" },
  { value: "Salvatore Ferragamo" },
  { value: "Bally" },
  { value: "Tod's" },
  { value: "Lanvin" },
  { value: "Hugo Boss" },
  { value: "Cole Haan" },
  { value: "Steve Madden" },
  { value: "Aldo" },
  { value: "Nine West" },
  { value: "UGG" },
  { value: "Birkenstock" },
  { value: "Teva" },
  { value: "Keen" },
  { value: "Columbia" },
  { value: "The North Face" },
  { value: "Sorel" },
  { value: "Sperry" },
  { value: "Toms" },
  { value: "Fila" },
  { value: "Keds" },
  { value: "Superga" },
  { value: "Onitsuka Tiger" },
  { value: "K-Swiss" },
  { value: "Lacoste" },
  { value: "Ralph Lauren" },
  { value: "Tommy Hilfiger" },
  { value: "Vionic" },
  { value: "Johnston & Murphy" },
  { value: "Florsheim" },
  { value: "Rockport" },
  { value: "Allen Edmonds" },
  { value: "Mephisto" },
  { value: "ECCO" },
  { value: "Geox" },
  { value: "Camper" },
  { value: "Caterpillar" },
  { value: "Wolverine" },
  { value: "Red Wing Shoes" },
  { value: "Timberland PRO" },
  { value: "Carhartt" },
  { value: "Ariat" },
  { value: "Bogs" },
  { value: "Justin Boots" },
  { value: "Chippewa" },
  { value: "Tony Lama" },
  { value: "L.L.Bean" },
  { value: "Sorel" },
  { value: "Kodiak" },
  { value: "Blundstone" },
  { value: "Caterpillar" },
  { value: "Columbia" },
  { value: "Hi-Tec" },
  { value: "Keen" },
  { value: "Oboz" },
  { value: "Salomon" },
  { value: "Vasque" },
  { value: "Lowa" },
  { value: "La Sportiva" },
  { value: "Scarpa" },
  { value: "Mammut" },
  { value: "Arc'teryx" },
  { value: "Black Diamond" },
  { value: "Petzl" },
  { value: "The North Face" },
];

export const typeList = [
  { value: "Sneakers", thumbnail: bg1 },
  { value: "Sandals", thumbnail: bg2 },
  { value: "Flip flops", thumbnail: bg3 },
  { value: "High - Heel", thumbnail: bg4 },
  { value: "Oxfords", thumbnail: bg5 },
  { value: "Athletics", thumbnail: bg6 },
  { value: "Boots - Ankle", thumbnail: bg7 },
];

export const newListProduct = [
  {
    id: 1,
    name: "Ang Lorem Ipsum ay ginagamit na modelo ng industriya ng pagpriprint at pagtytypeset. Ang Lorem Ipsum ang naging regular na modelo simula pa noong 1500s, ",
    description:
      "gdegrh asdasd asdasd gdegrh asdasd asdasd gdegrh asdasd asdasd gdegrh asdasd asdasd gdegrh asdasd asdasd, gdegrh asdasd asdasd gdegrh asdasd asdasd gdegrh asdasd asdasd gdegrh asdasd asdasd gdegrh asdasd asdasd,gdegrh asdasd asdasd gdegrh asdasd asdasd gdegrh asdasd asdasd gdegrh asdasd asdasd gdegrh asdasd asdasd,gdegrh asdasd asdasd gdegrh asdasd asdasd gdegrh asdasd asdasd gdegrh asdasd asdasd gdegrh asdasd asdasd,gdegrh asdasd asdasd gdegrh asdasd asdasd gdegrh asdasd asdasd gdegrh asdasd asdasd gdegrh asdasd asdasd,gdegrh asdasd asdasd gdegrh asdasd asdasd gdegrh asdasd asdasd gdegrh asdasd asdasd gdegrh asdasd asdasd,gdegrh asdasd asdasd gdegrh asdasd asdasd gdegrh asdasd asdasd gdegrh asdasd asdasd gdegrh asdasd asdasd,gdegrh asdasd asdasd gdegrh asdasd asdasd gdegrh asdasd asdasd gdegrh asdasd asdasd gdegrh asdasd asdasd,gdegrh asdasd asdasd gdegrh asdasd asdasd gdegrh asdasd asdasd gdegrh asdasd asdasd gdegrh asdasd asdasd,gdegrh asdasd asdasd gdegrh asdasd asdasd gdegrh asdasd asdasd gdegrh asdasd asdasd gdegrh asdasd asdasd,gdegrh asdasd asdasd gdegrh asdasd asdasd gdegrh asdasd asdasd gdegrh asdasd asdasd gdegrh asdasd asdasd,gdegrh asdasd asdasd gdegrh asdasd asdasd gdegrh asdasd asdasd gdegrh asdasd asdasd gdegrh asdasd asdasd,gdegrh asdasd asdasd gdegrh asdasd asdasd gdegrh asdasd asdasd gdegrh asdasd asdasd gdegrh asdasd asdasd,gdegrh asdasd asdasd gdegrh asdasd asdasd gdegrh asdasd asdasd gdegrh asdasd asdasd gdegrh asdasd asdasd,gdegrh asdasd asdasd gdegrh asdasd asdasd gdegrh asdasd asdasd gdegrh asdasd asdasd gdegrh asdasd asdasd,gdegrh asdasd asdasd gdegrh asdasd asdasd gdegrh asdasd asdasd gdegrh asdasd asdasd gdegrh asdasd asdasd",
    quantity: 5,
    originalPrice: 0.0,
    price: 6.0,
    status: null,
    images: [
      {
        id: 21,
        no: "21.jpg",
        url: "https://firebasestorage.googleapis.com/v0/b/datnv1-34493.appspot.com/o/ImageTest%2F21.jpg?alt=media",
        isProductImage: true,
      },
    ],
    shop: {
      id: 1,
      sName: "Shop2",
      sNumber: "3853",
      sStatus: null,
      sLogo:
        "https://firebasestorage.googleapis.com/v0/b/datnv1-34493.appspot.com/o/ShopImage%2Fshop1.png?alt=media",
      sAddress1:
        " Thon 2 thai son dien tien dien ban quan nam Thon 2 thai son dien tien dien ban quan nam n ban quan nam",
      sAddress2: "434",
      sFax: null,
      created_at: "2023-05-24T16:40:04",
      updated_at: "2023-05-24T16:40:04",
      user_id: 2,
    },
    created_at: "2023-05-24T16:40:05",
    updated_at: "2023-05-24T16:40:05",
  },
  {
    id: 2,
    name: "Ang Lorem Ipsum ay ginagamit na modelo ng industriya ng pagpriprint at pagtytypeset. Ang Lorem Ipsum ang naging regular na modelo simula pa noong 1500s,",
    description: "gdegrh asdasd asdasd",
    quantity: 50,
    originalPrice: 100000.0,
    price: 66000.0,
    status: null,
    images: [
      {
        id: 22,
        no: "22.jpg",
        url: "https://firebasestorage.googleapis.com/v0/b/datnv1-34493.appspot.com/o/ImageTest%2F22.jpg?alt=media",
        isProductImage: true,
      },
    ],
    shop: {
      id: 2,
      sName: "Shop5",
      sNumber: "0384",
      sStatus: null,
      sLogo:
        "https://firebasestorage.googleapis.com/v0/b/datnv1-34493.appspot.com/o/ShopImage%2Fshop2.png?alt=media",
      sAddress1: "Quang Binh",
      sAddress2: null,
      sFax: null,
      created_at: "2023-05-24T16:40:04",
      updated_at: "2023-05-24T16:40:04",
      user_id: 5,
    },
    created_at: "2023-05-24T16:40:05",
    updated_at: "2023-05-24T16:40:05",
  },
  {
    id: 3,
    name: "Matagal na nating alam na nakukuha ang atensyon ng nagbabasa ang nababasa na nilalaman ng pahina kapag tinitignan ang pagkakaayos. Ang punto ng paggamit ng Lorem Ipsum ay ito ay may humigit-kumulang na normal na distribusyion ng mga lettra, kesa sa paggamit ng 'Dito ang nilalam",
    description: "gdegrh asdasd asdasd",
    quantity: 55,
    originalPrice: 10000.0,
    price: 100000.0,
    status: null,
    images: [
      {
        id: 23,
        no: "23.jpg",
        url: "https://firebasestorage.googleapis.com/v0/b/datnv1-34493.appspot.com/o/ImageTest%2F23.jpg?alt=media",
        isProductImage: true,
      },
    ],
    shop: {
      id: 1,
      sName: "Shop2",
      sNumber: "3853",
      sStatus: null,
      sLogo:
        "https://firebasestorage.googleapis.com/v0/b/datnv1-34493.appspot.com/o/ShopImage%2Fshop1.png?alt=media",
      sAddress1: "",
      sAddress2: null,
      sFax: null,
      created_at: "2023-05-24T16:40:04",
      updated_at: "2023-05-24T16:40:04",
      user_id: 2,
    },
    created_at: "2023-05-24T16:40:05",
    updated_at: "2023-05-24T16:40:05",
  },
  {
    id: 4,
    name: "Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...",
    description:
      "gdegrh asdasd asdasd gdegrh asdasd asdasd gdegrh asdasd asdasd gdegrh asdasd asdasd gdegrh asdasd asdasd, gdegrh asdasd asdasd gdegrh asdasd asdasd gdegrh asdasd asdasd gdegrh asdasd asdasd gdegrh asdasd asdasd,gdegrh asdasd asdasd gdegrh asdasd asdasd gdegrh asdasd asdasd gdegrh asdasd asdasd gdegrh asdasd asdasd,gdegrh asdasd asdasd gdegrh asdasd asdasd gdegrh asdasd asdasd gdegrh asdasd asdasd gdegrh asdasd asdasd,gdegrh asdasd asdasd gdegrh asdasd asdasd gdegrh asdasd asdasd gdegrh asdasd asdasd gdegrh asdasd asdasd,gdegrh asdasd asdasd gdegrh asdasd asdasd gdegrh asdasd asdasd gdegrh asdasd asdasd gdegrh asdasd asdasd,gdegrh asdasd asdasd gdegrh asdasd asdasd gdegrh asdasd asdasd gdegrh asdasd asdasd gdegrh asdasd asdasd,gdegrh asdasd asdasd gdegrh asdasd asdasd gdegrh asdasd asdasd gdegrh asdasd asdasd gdegrh asdasd asdasd,gdegrh asdasd asdasd gdegrh asdasd asdasd gdegrh asdasd asdasd gdegrh asdasd asdasd gdegrh asdasd asdasd,gdegrh asdasd asdasd gdegrh asdasd asdasd gdegrh asdasd asdasd gdegrh asdasd asdasd gdegrh asdasd asdasd,gdegrh asdasd asdasd gdegrh asdasd asdasd gdegrh asdasd asdasd gdegrh asdasd asdasd gdegrh asdasd asdasd,gdegrh asdasd asdasd gdegrh asdasd asdasd gdegrh asdasd asdasd gdegrh asdasd asdasd gdegrh asdasd asdasd,gdegrh asdasd asdasd gdegrh asdasd asdasd gdegrh asdasd asdasd gdegrh asdasd asdasd gdegrh asdasd asdasd,gdegrh asdasd asdasd gdegrh asdasd asdasd gdegrh asdasd asdasd gdegrh asdasd asdasd gdegrh asdasd asdasd,gdegrh asdasd asdasd gdegrh asdasd asdasd gdegrh asdasd asdasd gdegrh asdasd asdasd gdegrh asdasd asdasd,gdegrh asdasd asdasd gdegrh asdasd asdasd gdegrh asdasd asdasd gdegrh asdasd asdasd gdegrh asdasd asdasd",
    quantity: 5,
    originalPrice: 0.0,
    price: 6.0,
    status: null,
    images: [
      {
        id: 21,
        no: "21.jpg",
        url: "https://firebasestorage.googleapis.com/v0/b/datnv1-34493.appspot.com/o/ImageTest%2F21.jpg?alt=media",
        isProductImage: true,
      },
    ],
    shop: {
      id: 1,
      sName: "Shop2",
      sNumber: "3853",
      sStatus: null,
      sLogo:
        "https://firebasestorage.googleapis.com/v0/b/datnv1-34493.appspot.com/o/ShopImage%2Fshop1.png?alt=media",
      sAddress1:
        " Thon 2 thai son dien tien dien ban quan nam Thon 2 thai son dien tien dien ban quan nam n ban quan nam",
      sAddress2: "434",
      sFax: null,
      created_at: "2023-05-24T16:40:04",
      updated_at: "2023-05-24T16:40:04",
      user_id: 2,
    },
    created_at: "2023-05-24T16:40:05",
    updated_at: "2023-05-24T16:40:05",
  },
  {
    id: 5,
    name: "pro1",
    description:
      "gdegrh asdasd asdasd gdegrh asdasd asdasd gdegrh asdasd asdasd gdegrh asdasd asdasd gdegrh asdasd asdasd, gdegrh asdasd asdasd gdegrh asdasd asdasd gdegrh asdasd asdasd gdegrh asdasd asdasd gdegrh asdasd asdasd,gdegrh asdasd asdasd gdegrh asdasd asdasd gdegrh asdasd asdasd gdegrh asdasd asdasd gdegrh asdasd asdasd,gdegrh asdasd asdasd gdegrh asdasd asdasd gdegrh asdasd asdasd gdegrh asdasd asdasd gdegrh asdasd asdasd,gdegrh asdasd asdasd gdegrh asdasd asdasd gdegrh asdasd asdasd gdegrh asdasd asdasd gdegrh asdasd asdasd,gdegrh asdasd asdasd gdegrh asdasd asdasd gdegrh asdasd asdasd gdegrh asdasd asdasd gdegrh asdasd asdasd,gdegrh asdasd asdasd gdegrh asdasd asdasd gdegrh asdasd asdasd gdegrh asdasd asdasd gdegrh asdasd asdasd,gdegrh asdasd asdasd gdegrh asdasd asdasd gdegrh asdasd asdasd gdegrh asdasd asdasd gdegrh asdasd asdasd,gdegrh asdasd asdasd gdegrh asdasd asdasd gdegrh asdasd asdasd gdegrh asdasd asdasd gdegrh asdasd asdasd,gdegrh asdasd asdasd gdegrh asdasd asdasd gdegrh asdasd asdasd gdegrh asdasd asdasd gdegrh asdasd asdasd,gdegrh asdasd asdasd gdegrh asdasd asdasd gdegrh asdasd asdasd gdegrh asdasd asdasd gdegrh asdasd asdasd,gdegrh asdasd asdasd gdegrh asdasd asdasd gdegrh asdasd asdasd gdegrh asdasd asdasd gdegrh asdasd asdasd,gdegrh asdasd asdasd gdegrh asdasd asdasd gdegrh asdasd asdasd gdegrh asdasd asdasd gdegrh asdasd asdasd,gdegrh asdasd asdasd gdegrh asdasd asdasd gdegrh asdasd asdasd gdegrh asdasd asdasd gdegrh asdasd asdasd,gdegrh asdasd asdasd gdegrh asdasd asdasd gdegrh asdasd asdasd gdegrh asdasd asdasd gdegrh asdasd asdasd,gdegrh asdasd asdasd gdegrh asdasd asdasd gdegrh asdasd asdasd gdegrh asdasd asdasd gdegrh asdasd asdasd",
    quantity: 5,
    originalPrice: 0.0,
    price: 6.0,
    status: null,
    images: [
      {
        id: 21,
        no: "21.jpg",
        url: "https://firebasestorage.googleapis.com/v0/b/datnv1-34493.appspot.com/o/ImageTest%2F21.jpg?alt=media",
        isProductImage: true,
      },
    ],
    shop: {
      id: 1,
      sName: "Shop2",
      sNumber: "3853",
      sStatus: null,
      sLogo:
        "https://firebasestorage.googleapis.com/v0/b/datnv1-34493.appspot.com/o/ShopImage%2Fshop1.png?alt=media",
      sAddress1:
        " Thon 2 thai son dien tien dien ban quan nam Thon 2 thai son dien tien dien ban quan nam n ban quan nam",
      sAddress2: "434",
      sFax: null,
      created_at: "2023-05-24T16:40:04",
      updated_at: "2023-05-24T16:40:04",
      user_id: 2,
    },
    created_at: "2023-05-24T16:40:05",
    updated_at: "2023-05-24T16:40:05",
  },
];

export const shop_manager_promo = [
  {
    id: 1,
    no: 1,
    title: "Quản lí sản phẩm",
    description:
      "Cập nhật số lượng, tình trạng, giá cả của các sản phẩm trong shop của bạn ",
    thumbnail: bg1,
  },
  {
    id: 2,
    no: 1,
    title: "Quản lí thông tin",
    description:
      "Cập nhật thông tin, địa chỉ, link shop để người dùng dễ dàng tìm đến bạn",
    thumbnail: bg1,
  },
  {
    id: 3,
    no: 1,
    title: "Thêm sản phẩm mới",
    description: "Hãy thêm sản phẩm mới vào shop của bạn",
    thumbnail: bg1,
  },
];

export const shop_main_promo = [
  {
    id: 1,
    no: 1,
    title: "Quản lí sản phẩm",
    description:
      "Cập nhật số lượng, tình trạng, giá cả của các sản phẩm trong shop của bạn ",
    thumbnail: promoBg1,
  },
  {
    id: 2,
    no: 1,
    title: "Quản lí thông tin",
    description:
      "Cập nhật thông tin, địa chỉ, link shop để người dùng dễ dàng tìm đến bạn",
    thumbnail: promoBg2,
  },
  {
    id: 3,
    no: 1,
    title: "Thêm sản phẩm mới",
    description: "Liên kết sản phẩm mới vào shop của bạn",
    thumbnail: promoBg3,
  },
];
