export default {
  //Authexport
  IS_LOGIN: "IS_LOGIN",
  LOGIN: "LOGIN",
  SIGNUP: "SIGNUP",
  GET_DETAIL_USERS: "GET_DETAIL_USERS",
  CLEAR_REDUX_STATE: "CLEAR_REDUX_STATE",

  //Search Screen
  GET_LIST_SEARCH: "GET_LIST_SEARCH",
  UPDATE_CATEGORY_INDEX: "UPDATE_CATEGORY_INDEX",
  SHOW_ALL_CATEGORY: "SHOW_ALL_CATEGORY",
  // PAGE: "PAGE",
  // PAGE_PRODUCT: "PAGE_PRODUCT",
  // PAGE_POST: "PAGE_POST",
  SEARCH_TEXT: "SEARCH_TEXT",
  IS_MAIN_VIEW_DISPLAY: "IS_MAIN_VIEW_DISPLAY",
  IS_LOADING: "IS_LOADING",
  SHOW_FILTER_MODEL: "SHOW_FILTER_MODEL",

  //Fileter
  NOW_RANGE_MINMAX: "NOW_RANGE_MINMAX",
  BRAND_SELECTED_LIST: "BRAND_SELECTED_LIST",
  TYPE_SELECTED_LIST: "TYPE_SELECTED_LIST",
  UPDATE_APPLY_FILTER: "UPDATE_APPLY_FILTER",
  IS_CHANGE_FILTER: "IS_CHANGE_FILTER",

  //ReloadScreen
  RELOAD_SHOP_MANAGER_SCREEN: "RELOAD_SHOP_MANAGER_SCREEN",
};
